name: league_of_legends_api
description: A Dart client for the Data Dragon League of Legends API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  http: ^1.2.2

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
